import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const customFont = localFont({
  src: [
    {
      path: "../../public/font/TerminessNerdFontMono-Regular.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../../public/font/TerminessNerdFontMono-Italic.ttf",
      style: "italic",
      weight: "400",
    },
    {
      path: "../../public/font/TerminessNerdFontMono-Bold.ttf",
      style: "bold",
      weight: "400",
    },
  ],
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${customFont.variable} antialiased dark`}>
        {children}
      </body>
    </html>
  );
}
